import sys
import time
import os
from myImageLib import dirrec
from shutil import copy

"""
Generete preview images of given folder.

Assumed folder structure:
Folder
|- 00
  |- 8-bit
    |- 00000.tif
    |- ...
  |- raw
|- preview (newly generated by this script)
  |- 00.tif
  |- ...

The script will copy all the 00000.tif under 8-bit folder to a new "preview" folder

USAGE
=====
python gen_preview.py folder

folder should be two levels above the 00000.tif file.
Deeper directories won't be searched.

TEST
====
python gen_preview.py test_images\gen_preview\day1

LOG
===
test_images\gen_preview\day1\00\8-bit\00000.tif -> test_images\gen_preview\day1\preview\00.tif

EDIT
====
Dec 12, 2021 -- Initial commit
Dec 13, 2021 -- `cp` command is not platform independent. Use python native tools `shutil.copy` instead.
"""

if __name__=="__main__":
    folder = sys.argv[1]
    sfL = next(os.walk(folder))[1]
    print(sfL)
    # create preview folder
    preview_folder = os.path.join(folder, "preview")
    if os.path.exists(preview_folder) == False:
        os.makedirs(preview_folder)
    for sf in sfL:
        subfolder = os.path.join(folder, sf)
        img_dir = os.path.join(subfolder, "8-bit", "00000.tif")
        if os.path.exists(img_dir):
            dest_dir = os.path.join(preview_folder, sf + ".tif")
            print(time.asctime() + " \\ {0} -> {1}".format(img_dir, dest_dir))
            copy(img_dir, dest_dir)
