import sys
import time
import os
from myImageLib import dirrec

"""
Generete preview images of given folder.

Assumed folder structure:
Folder
|- 00
  |- 8-bit
    |- 00000.tif
    |- ...
  |- raw
|- preview (newly generated by this script)
  |- 00.tif
  |- ...

The script will copy all the 00000.tif under 8-bit folder to a new "preview" folder

USAGE
=====
python gen_preview.py folder

folder should be two levels above the 00000.tif file. 
Deeper directories won't be searched.

TEST
====

LOG
===

EDIT
====
Dec 12, 2021 -- Initial commit
"""

if __name__=="__main__":
    folder = sys.argv[1]
    sfL = next(os.walk(folder))[1]
    print(sfL)
    # create preview folder
    preview_folder = os.path.join(folder, "preview")
    if os.path.exists(preview_folder) == False:
        os.makedirs(preview_folder)
    for sf in sfL:
        subfolder = os.path.join(folder, sf)
        img_dir = os.path.join(subfolder, "8-bit", "00000.tif")
        if os.path.exists(img_dir):
            dest_dir = os.path.join(preview_folder, sf + ".tif")
            os.system("cp {0} {1} -v".format(img_dir, dest_dir))
