"""
Put PIV data from separated text files into a .mat file, in order to keep the number of files small and meantime save some storage space.

.. rubric:: Syntax

.. code-block:: console

   python wrap_piv.py piv_folder

* piv_folder: piv data folder containing .csv files

.. note::

   If the given folder contains .txt files generated by ImageJ PIV, we need to run `rename_ij_piv.py` first to convert the file name and format.

.. warning::

   The original .csv files will be deleted once the .mat file is saved.

.. rubric:: Edit

* Dec 01, 2022 -- Initial commit.
* Dec 19, 2022 -- Add a warning of deleting original .csv files.
* Jan 05, 2023 -- (i) Adapt myimagelib import style. (ii) Add screen info.
* Feb 08, 2023 -- Rewrite in function wrapper form, to make autodoc work properly. (autodoc import the script and execute it, so anything outside ``if __name__=="__main__"`` will be executed, causing problems)
"""



if __name__ == "__main__":

   from myimagelib.myImageLib import readdata, show_progress
   from myimagelib.pivLib import compact_PIV
   import os
   import sys

   piv_folder = sys.argv[1]

   l = readdata(piv_folder, "csv")
   nFiles = len(l)
   print("{:d} files found".format(nFiles))
   print("Wrapping into .mat file ...")

   cpiv = compact_PIV(l)
   cpiv.to_mat(piv_folder.rstrip(os.sep) + ".mat")

   print("Clean up text files ...")
   for num, i in l.iterrows():
      show_progress((num+1)/nFiles, num)
      os.remove(i.Dir)
