from myImageLib import readdata, show_progress
from pivLib import compact_PIV
import os
import sys

"""
wrap_piv
========

Put PIV data from separated text files into a .mat file, in order to keep the number of files small and meantime save some storage space.

.. rubric:: Syntax

.. code-block:: console

   python wrap_piv.py piv_folder

* piv_folder: piv data folder containing .csv files

.. note::

   If the given folder contains .txt files generated by ImageJ PIV, we need to run `rename_ij_piv.py` first to convert the file namme and format.

.. rubric:: Edit

* Dec 1, 2022 -- Initial commit.
"""

piv_folder = sys.argv[1]

l = readdata(piv_folder, "csv")
nFiles = len(l)
print("{:d} files found".format(nFiles))

cpiv = compact_PIV(l)
cpiv.to_mat(piv_folder.rstrip(os.sep) + ".mat")

print("Clean up text files ...")
for num, i in l.iterrows():
    show_progress((num+1)/nFiles, num)
    os.remove(i.Dir)
